# Generated by Django 4.2 on 2023-05-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuardianName', models.CharField(max_length=80)),
                ('GuardianMobileNo', models.CharField(max_length=80)),
                ('GuardianRelship', models.CharField(max_length=80)),
                ('GuardianAddress', models.CharField(max_length=100)),
                ('DischargeDate', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(max_length=70)),
                ('AddmissionNumber', models.CharField(max_length=100)),
                ('AddmissionDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Addmission',
            },
        ),
        migrations.CreateModel(
            name='AdmissionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered_by', models.CharField(max_length=100)),
                ('AdmissionDate', models.DateField()),
                ('AdmissionReason', models.TextField()),
                ('BedType', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Note', models.TextField()),
                ('patient_priority', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AdmissionOrder',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppointmentDate', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('AppointmentNumber', models.CharField(max_length=100)),
                ('queue_number', models.IntegerField()),
            ],
            options={
                'permissions': [('Approve_appointment', 'Can approve Appointment')],
            },
        ),
        migrations.CreateModel(
            name='AssignBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromDate', models.DateTimeField()),
                ('ToDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AssignBed',
            },
        ),
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BedNO', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Beds',
            },
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dischargeStatus', models.CharField(max_length=100)),
                ('Operation', models.TextField()),
                ('Note', models.TextField()),
                ('Diagnosis', models.TextField()),
            ],
            options={
                'db_table': 'Discharge',
            },
        ),
        migrations.CreateModel(
            name='EmergencyRoomVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitDateTime', models.DateTimeField(auto_now_add=True)),
                ('DischargeDateTime', models.DateTimeField(blank=True, null=True)),
                ('EmergencyNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('EmergencyName', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('VisitNumber', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('Approve_visit', 'Can approve EmergencyVisit')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChiefComplaint', models.TextField()),
                ('Allergies', models.TextField()),
                ('Vitalsigns', models.TextField()),
                ('CurrentMedications', models.TextField()),
                ('FamilyMedicalHistory', models.TextField()),
                ('PastMedicalHistory', models.TextField()),
                ('Triage_dateTime', models.DateTimeField()),
                ('TriageCategory', models.CharField(max_length=60)),
                ('Assessment', models.TextField()),
                ('Comment', models.TextField()),
            ],
            options={
                'db_table': 'EmergencyTriage',
            },
        ),
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication_date', models.DateField()),
                ('Medicition_time', models.TimeField()),
                ('Medication_dose', models.CharField(max_length=100)),
                ('Medicition_Remarks', models.TextField()),
            ],
            options={
                'db_table': 'MedicationDose',
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescriptionDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Dose', models.CharField(max_length=100)),
                ('DoseInterval', models.CharField(max_length=150)),
                ('DoseDuration', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'MedicinePrescriptionDetials',
            },
        ),
        migrations.CreateModel(
            name='OperationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OperationCategory',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationName', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=200)),
                ('CategoryName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.operationcategory')),
            ],
            options={
                'db_table': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='PatientDeath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Death_Date', models.DateTimeField()),
                ('Death_Reason', models.TextField()),
            ],
            options={
                'db_table': 'PatientDeath',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientFirstName', models.CharField(max_length=60)),
                ('PatientMiddleName', models.CharField(max_length=60)),
                ('PatientLastName', models.CharField(max_length=60)),
                ('PatientFullName', models.CharField(max_length=100)),
                ('PatientAge', models.CharField(max_length=60)),
                ('PatientGender', models.CharField(max_length=60)),
                ('PatientMobileNo', models.CharField(blank=True, max_length=50, null=True)),
                ('PatientVillage', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientDistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientMaritalStatus', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Referrel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalName', models.TextField()),
                ('Referel_Date', models.DateField()),
                ('Referel_Reason', models.TextField()),
            ],
            options={
                'db_table': 'Referrel',
            },
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hr.departments')),
            ],
            options={
                'db_table': 'Room_category',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_NO', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Room_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.room_category')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Patient_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationDate', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.addmission')),
                ('Appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.appointments')),
                ('Operation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='APEN.operations')),
            ],
            options={
                'db_table': 'Patient_operation',
            },
        ),
        migrations.CreateModel(
            name='NurseNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_dateTime', models.DateTimeField()),
                ('Note', models.TextField()),
                ('Comment', models.TextField()),
                ('Admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.addmission')),
                ('Nurse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
            ],
            options={
                'db_table': 'NurseNotes',
            },
        ),
        migrations.CreateModel(
            name='MedicinesPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription_Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
                ('Ordered_by', models.TextField()),
                ('PrescriptionNo', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('Admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.addmission')),
                ('Appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.appointments')),
                ('Visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.emergencyroomvisit')),
            ],
            options={
                'db_table': 'MedicinesPrescription',
            },
        ),
    ]
