# Generated by Django 4.2 on 2023-05-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APEN', '0001_initial'),
        ('LRPD', '0001_initial'),
        ('Hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineprescriptiondetials',
            name='MedicineName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LRPD.pharmacy_medicine'),
        ),
        migrations.AddField(
            model_name='medicineprescriptiondetials',
            name='PrescriptionNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APEN.medicinesprescription'),
        ),
        migrations.AddField(
            model_name='medicationdose',
            name='Admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.addmission'),
        ),
        migrations.AddField(
            model_name='medicationdose',
            name='Medication_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APEN.medicineprescriptiondetials'),
        ),
        migrations.AddField(
            model_name='medicationdose',
            name='Visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.emergencyroomvisit'),
        ),
        migrations.AddField(
            model_name='emergencytriage',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_Doctor', to='Hr.employee'),
        ),
    ]
