# Generated by Django 4.2 on 2023-05-27 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APEN', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytriage',
            name='TriageNurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Triage_nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencytriage',
            name='Visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APEN.emergencyroomvisit'),
        ),
        migrations.AddField(
            model_name='emergencyroomvisit',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APEN.patients'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='Admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.addmission'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='Admission_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.admissionorder'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='Visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.emergencyroomvisit'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='death',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.patientdeath'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='referrel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.referrel'),
        ),
        migrations.AddField(
            model_name='beds',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.room'),
        ),
        migrations.AddField(
            model_name='assignbed',
            name='Admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.addmission'),
        ),
        migrations.AddField(
            model_name='assignbed',
            name='Bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APEN.beds'),
        ),
        migrations.AddField(
            model_name='assignbed',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APEN.room'),
        ),
        migrations.AddField(
            model_name='assignbed',
            name='Visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.emergencyroomvisit'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Doctor', to='Hr.employee'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APEN.patients'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='Receptionist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Receptionist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointments',
            name='jobtypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.jobtype'),
        ),
        migrations.AddField(
            model_name='admissionorder',
            name='Appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.appointments'),
        ),
        migrations.AddField(
            model_name='admissionorder',
            name='Visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.emergencyroomvisit'),
        ),
        migrations.AddField(
            model_name='addmission',
            name='Admission_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.admissionorder'),
        ),
    ]
