# Generated by Django 4.2 on 2023-05-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depart_Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_sections', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Discriptions', models.CharField(blank=True, max_length=400, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('father_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('mother_name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=50)),
                ('marital', models.CharField(max_length=50)),
                ('emp_number', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=1000)),
                ('emergency_contect', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='images/profile')),
                ('address', models.CharField(max_length=100)),
                ('Employee_state', models.CharField(default='Pending', max_length=100)),
                ('schedula', models.CharField(blank=True, max_length=100, null=True)),
                ('schedula_state', models.BooleanField(blank=True, default=False, null=True)),
                ('is_terminated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('appprovedwho', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('Approve_employee', 'Can approve Employee')],
            },
        ),
        migrations.CreateModel(
            name='Employee_exit_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_appoitment_rel', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCatogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('n_days', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(max_length=100)),
                ('shift_date', models.CharField(max_length=300)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Discriptions', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.directorate')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('base_salary', models.FloatField()),
                ('fixed_allow', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('Specialization', models.CharField(max_length=100)),
                ('Documents', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeBank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.leavecatogory')),
                ('JobDetails', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manage_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='inactive', max_length=400, null=True)),
                ('existday', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.work_shift')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(blank=True, max_length=200, null=True)),
                ('base_pay', models.FloatField(default=0.0)),
                ('appprovedwho', models.CharField(max_length=500)),
                ('TermsOfService', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('job_state', models.CharField(default='Pending', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('depar_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.depart_sections')),
                ('department_all', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.departments')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.directorate')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.jobtype')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.salary')),
                ('secretory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.secretary')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('documents', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='exited_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('dayHappen', models.DateField(blank=True, default='', null=True)),
                ('timeHappen', models.TimeField(blank=True, default='', null=True)),
                ('document', models.FileField(upload_to='')),
                ('exit_state', models.CharField(default='Pending', max_length=50)),
                ('appprovedwho', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('exit_emp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
                ('exit_emp_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee_exit_category')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('banks', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.banks')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startday', models.DateField()),
                ('endtday', models.DateField()),
                ('reason', models.TextField()),
                ('State', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('document', models.FileField(upload_to='')),
                ('leavesdays', models.CharField(blank=True, max_length=100, null=True)),
                ('approvedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
                ('leave_ct', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.leavecatogory')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.title'),
        ),
        migrations.AddField(
            model_name='departments',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.directorate'),
        ),
        migrations.AddField(
            model_name='depart_sections',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Hr.departments'),
        ),
        migrations.CreateModel(
            name='Attandence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('today_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=400, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hr.work_shift')),
            ],
        ),
    ]
