# Generated by Django 4.2 on 2023-05-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Hr', '0001_initial'),
        ('APEN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=150)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'ExamCategory',
            },
        ),
        migrations.CreateModel(
            name='Lab_Blood_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResultValue', models.CharField(max_length=200)),
                ('flag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Lab_Blood_Results',
            },
        ),
        migrations.CreateModel(
            name='Lab_ExaminationParameters_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResultValue', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Lab_ExaminationParameters_Results',
            },
        ),
        migrations.CreateModel(
            name='LabEquipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('Order_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'LabEquipmentOrder',
            },
        ),
        migrations.CreateModel(
            name='LabExaminationParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('ParameterName', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LabExaminationParameters',
            },
        ),
        migrations.CreateModel(
            name='LabTest_Blood_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NormalRange', models.CharField(max_length=70)),
                ('TestUnit', models.CharField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LabTest_Blood_Properties',
            },
        ),
        migrations.CreateModel(
            name='LabTestGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=100)),
                ('GroupDescription', models.CharField(max_length=140)),
                ('sampleType', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LabTestGroups',
            },
        ),
        migrations.CreateModel(
            name='LabTestOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'LabTestOrderDetails',
            },
        ),
        migrations.CreateModel(
            name='LabTestOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered_by', models.TextField()),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
                ('TestOrderNumber', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LabTestOrders',
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result_date', models.DateField(auto_now_add=True)),
                ('CollectionDate', models.DateField()),
                ('Comment', models.TextField()),
            ],
            options={
                'db_table': 'LabTestResult',
            },
        ),
        migrations.CreateModel(
            name='LabTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('TestDescription', models.CharField(max_length=140)),
                ('SampleType', models.CharField(max_length=50)),
                ('ShortName', models.CharField(max_length=100)),
                ('TestNumber', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LabTests',
            },
        ),
        migrations.CreateModel(
            name='LabTestSubGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubGroupName', models.CharField(max_length=100)),
                ('SubGroupDescription', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LabTestSubGroups',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MedicineOrder',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'MedicineOrderDetails',
            },
        ),
        migrations.CreateModel(
            name='pharmacy_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('Expire_date', models.DateField()),
                ('Total_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pharmacy_medicine',
            },
        ),
        migrations.CreateModel(
            name='PharmacyTransection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('box', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('Total_quantity', models.PositiveIntegerField()),
                ('manufacturing_date', models.DateField()),
                ('BatchNO', models.CharField(max_length=100)),
                ('supplier_price', models.CharField(max_length=100)),
                ('Expire_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PharmacyTransection',
            },
        ),
        migrations.CreateModel(
            name='RadiologyExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamName', models.CharField(max_length=100)),
                ('ExamDescription', models.CharField(max_length=140)),
                ('ExamNumber', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LRPD.examcategory')),
            ],
            options={
                'db_table': 'RadiologyExam',
            },
        ),
        migrations.CreateModel(
            name='RadiologyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered_by', models.TextField()),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
                ('RadiologyOrderNumber', models.CharField(max_length=100)),
                ('Admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.addmission')),
                ('Appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.appointments')),
                ('Visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APEN.emergencyroomvisit')),
            ],
            options={
                'db_table': 'RadiologyOrder',
            },
        ),
        migrations.CreateModel(
            name='RadiologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result_date', models.DateField(auto_now_add=True)),
                ('CollectionDate', models.DateField()),
                ('Collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_by_radio', to='Hr.employee')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_radio', to='Hr.employee')),
                ('RadiologyOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LRPD.radiologyorders')),
            ],
            options={
                'db_table': 'RadiologyResult',
            },
        ),
        migrations.CreateModel(
            name='RadiologyResultDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Findings', models.TextField()),
                ('Impressions', models.TextField()),
                ('Recommendations', models.TextField()),
                ('Comments', models.TextField()),
                ('Result_Files', models.FileField(null=True, upload_to='')),
                ('RadiologyExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LRPD.radiologyexam')),
                ('Radiology_Result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LRPD.radiologyresult')),
            ],
            options={
                'db_table': 'RadiologyResultDetails',
            },
        ),
        migrations.CreateModel(
            name='RadiologyOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RadiologyExam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LRPD.radiologyexam')),
                ('RadiologyOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LRPD.radiologyorders')),
            ],
            options={
                'db_table': 'RadiologyOrderDetails',
            },
        ),
        migrations.CreateModel(
            name='RadiologyEquipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.equipment')),
            ],
            options={
                'db_table': 'RadiologyEquipmentOrder',
            },
        ),
    ]
